version: '2.3'
services:
  redis:
    image: redis:5.0.3
    ports:
      - "6379:6379"

  service:
    runtime: nvidia
    image: registry.insight-centre.org/sit/mps/felipe-phd/semantic-image-segmentation:dev
    command: echo "ok"
    build:
      context: '.'
      dockerfile: 'Dockerfile'
      args:
        - SIT_PYPI_USER_VAR=${SIT_PYPI_USER}
        - SIT_PYPI_PASS_VAR=${SIT_PYPI_PASS}
    depends_on:
      - redis
    environment:
      - SIT_PYPI_USER=${SIT_PYPI_USER}
      - SIT_PYPI_PASS=${SIT_PYPI_PASS}
    volumes:
      - ./:/service

